name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        run: docker build -t ahernandez96/react-test -f ./frontend/Dockerfile.dev ./frontend && docker run -e CI=true ahernandez96/react-test npm test

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ahernandez96/docker-app1:latest

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-app1
          environment_name: Dockerapp1-env
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy.zip

      # - name: Generate build number
      #   id: buildnumber
      #   uses: einaregilsson/build-number@v3
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-app1
      #     environment_name: Dockerapp1-env2
      #     existing_bucket_name: elasticbeanstalk-us-east-2-306613870728
      #     region: us-east-2
      #     version_label: docker-app1-${{ steps.buildnumber.outputs.build_number }}
      #     deployment_package: deploy.zip